# Generated by Django 2.2.4 on 2019-08-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_book', models.CharField(default='', max_length=500)),
                ('book', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
                ('sub_cat', models.CharField(max_length=200)),
                ('read', models.BooleanField()),
                ('link', models.CharField(max_length=500)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
